import 'bootstrap/dist/css/bootstrap.css';
import * as React from "react";
import * as ReactDOM from "react-dom";
import "./index.css";
import "./App.css";
import App from "./App";
import registerServiceWorker from "./registerServiceWorker";
require('../src/App.css');
ReactDOM.render(<App />, document.getElementById("root"));
// registerServiceWorker();
